name: Multi-architecture environment images


on:
  workflow_dispatch:
    inputs:
      no_docker_cache:
        description: 'Set this to a non-empty string to disable docker caching'
        required: false
        default: ''


env:
  GH_PKG_PREFIX: docker.pkg.github.com/egraff/xplat-ci-images/


jobs:
  buildroot_toolchain:
    name: Buildroot toolchain
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # 64-bit PowerPC big-endian (ppc64)
          - toolchain_arch_name: powerpc64
            img_arch_prefix: ppc64_pseries_
            br2_config_file: ppc64_pseries
            linux_defconfig_file: powerpc64_pseries_defconfig

          # 32-bit PowerPC big-endian (ppc)
          - toolchain_arch_name: powerpc
            img_arch_prefix: ppc_g3beige_
            br2_config_file: ppc_g3beige
            linux_defconfig_file: powerpc_g3beige_defconfig

          # x86_64
          - toolchain_arch_name: x64
            img_arch_prefix: x86_64_
            br2_config_file: x86_64
            linux_defconfig_file: x86_64_defconfig

    steps:
      - name: Check out code
        uses: actions/checkout@v2.3.4

      - name: Login to GitHub Package Registry
        shell: bash
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login https://docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Pull dependency images from GitHub Package Registry
        shell: bash
        run: |
          docker pull ${{ env.GH_PKG_PREFIX }}buildroot_with_dl_cache:latest
          docker tag  ${{ env.GH_PKG_PREFIX }}buildroot_with_dl_cache:latest buildroot

      - name: Pull cache images from GitHub Package Registry
        if: ${{ github.event.inputs.no_docker_cache == '' }}
        shell: bash
        run: |
          (
            docker pull ${{ env.GH_PKG_PREFIX }}${{ matrix.img_arch_prefix }}toolchain_build:latest &&
            docker tag  ${{ env.GH_PKG_PREFIX }}${{ matrix.img_arch_prefix }}toolchain_build:latest buildroot_toolchain_build
          ) || true

      - name: Check disk usage
        run: |
          docker system df
          df -h

      - name: Build toolchain_build image
        shell: bash
        run: |
          rm -rf .br2-tree
          mkdir -p .br2-tree/configs
          rsync --archive --ignore-times --exclude '*~' --exclude '.git*' resources/br2/trees/default/ .br2-tree/
          cp resources/linux_configs/${{ matrix.linux_defconfig_file }} .br2-tree/linux-5.4.config
          (cd resources/br2/configs/toolchains && cat include/common_header ${{ matrix.br2_config_file }}) > .br2-tree/configs/config_defconfig
          docker build . \
            --tag buildroot_toolchain_build \
            --file resources/docker/buildroot_makebuild.Dockerfile \
            --build-arg baseimage=buildroot \
            --build-arg make_target=toolchain \
            --cache-from buildroot_toolchain_build

      - name: Check disk usage
        run: |
          docker system df
          df -h

      - name: Push to GitHub Packages
        shell: bash
        run: |
          docker tag buildroot_toolchain_build ${{ env.GH_PKG_PREFIX }}${{ matrix.img_arch_prefix }}toolchain_build:$GITHUB_SHA
          docker tag buildroot_toolchain_build ${{ env.GH_PKG_PREFIX }}${{ matrix.img_arch_prefix }}toolchain_build:latest
          docker push ${{ env.GH_PKG_PREFIX }}${{ matrix.img_arch_prefix }}toolchain_build:$GITHUB_SHA
          docker push ${{ env.GH_PKG_PREFIX }}${{ matrix.img_arch_prefix }}toolchain_build:latest

      - name: Copy toolchain to output folder
        shell: bash
        run: |
          rm -rf .dockersrv
          mkdir -p .dockersrv/output
          docker run \
            --rm \
            -v ${PWD}/.dockersrv:/srv \
            buildroot_toolchain_build \
            bash -c "tar -czf /srv/output/toolchain_${{ matrix.toolchain_arch_name }}.tar.gz -C /root/buildroot/output/host/ ."

      - name: Upload toolchain as artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.toolchain_arch_name }}_toolchain
          path: |
            .dockersrv/output/toolchain_${{ matrix.toolchain_arch_name }}.tar.gz


  buildroot_images:
    name: Buildroot images
    needs: buildroot_toolchain
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # 64-bit PowerPC big-endian (ppc64)
          - runimage_arch_name: powerpc64
            img_arch_prefix: ppc64_pseries_
            br2_config_file: ppc64_pseries

          # 32-bit PowerPC big-endian (ppc)
          - runimage_arch_name: powerpc
            img_arch_prefix: ppc_g3beige_
            br2_config_file: ppc_g3beige

          # x86_64
          - runimage_arch_name: x64
            img_arch_prefix: x86_64_
            br2_config_file: x86_64

    steps:
      - name: Check out code
        uses: actions/checkout@v2.3.4

      - name: Login to GitHub Package Registry
        shell: bash
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login https://docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Pull dependency images from GitHub Package Registry
        shell: bash
        run: |
          docker pull ${{ env.GH_PKG_PREFIX }}${{ matrix.img_arch_prefix }}toolchain_build:$GITHUB_SHA
          docker tag  ${{ env.GH_PKG_PREFIX }}${{ matrix.img_arch_prefix }}toolchain_build:$GITHUB_SHA buildroot_toolchain_build

      - name: Pull cache images from GitHub Package Registry
        if: ${{ github.event.inputs.no_docker_cache == '' }}
        shell: bash
        run: |
          (
            docker pull ${{ env.GH_PKG_PREFIX }}${{ matrix.img_arch_prefix }}images_build:latest &&
            docker tag  ${{ env.GH_PKG_PREFIX }}${{ matrix.img_arch_prefix }}images_build:latest images_build
          ) || true

      - name: Check disk usage
        run: |
          docker system df
          df -h

      - name: Build images_build image
        shell: bash
        run: |
          rm -rf .br2-tree
          mkdir -p .br2-tree/configs
          mkdir -p .br2-tree/build_customizations
          rsync --archive --ignore-times --exclude '*~' --exclude '.git*' resources/br2/trees/default/ .br2-tree/
          rsync --archive --ignore-times --exclude '*~' --exclude '.git*' resources/br2/build_customizations/default/ .br2-tree/build_customizations/
          (cd resources/br2/configs/images && cat include/common_header ${{ matrix.br2_config_file }}) > .br2-tree/configs/config_defconfig
          docker build . \
            --tag images_build \
            --file resources/docker/buildroot_makebuild.Dockerfile \
            --build-arg baseimage=buildroot_toolchain_build \
            --cache-from images_build

      - name: Check disk usage
        run: |
          docker system df
          df -h

      - name: Push to GitHub Packages
        run: |
          docker tag images_build ${{ env.GH_PKG_PREFIX }}${{ matrix.img_arch_prefix }}images_build:$GITHUB_SHA
          docker tag images_build ${{ env.GH_PKG_PREFIX }}${{ matrix.img_arch_prefix }}images_build:latest
          docker push ${{ env.GH_PKG_PREFIX }}${{ matrix.img_arch_prefix }}images_build:$GITHUB_SHA
          docker push ${{ env.GH_PKG_PREFIX }}${{ matrix.img_arch_prefix }}images_build:latest

      - name: Build images_build_final image
        shell: bash
        run: |
          rm -rf .br2-tree
          mkdir -p .br2-tree/build_customizations
          rsync --archive --ignore-times --exclude '*~' --exclude '.git*' resources/br2/build_customizations/sshserver/ .br2-tree/build_customizations/
          rsync --archive --ignore-times --exclude '*~' --exclude '.git*' resources/br2/build_customizations/host_overlay/ .br2-tree/build_customizations/
          rsync --archive --ignore-times --exclude '*~' --exclude '.git*' resources/br2/build_customizations/host_mnt/ .br2-tree/build_customizations/
          docker build . \
            --tag images_build_final \
            --file resources/docker/buildroot_makebuild.Dockerfile \
            --build-arg baseimage=images_build

      - name: Build runimage
        shell: bash
        run: |
          docker build . \
            --tag runimage \
            --file resources/docker/runimage.Dockerfile \
            --build-arg buildimage=images_build_final \
            --build-arg arch=${{ matrix.runimage_arch_name }}

      - name: Push to GitHub Packages
        run: |
          docker tag runimage ${{ env.GH_PKG_PREFIX }}${{ matrix.img_arch_prefix }}runimage:$GITHUB_SHA
          docker tag runimage ${{ env.GH_PKG_PREFIX }}${{ matrix.img_arch_prefix }}runimage:latest
          docker tag runimage ${{ env.GH_PKG_PREFIX }}runimage_${{ matrix.runimage_arch_name }}:$GITHUB_SHA
          docker tag runimage ${{ env.GH_PKG_PREFIX }}runimage_${{ matrix.runimage_arch_name }}:latest
          docker push ${{ env.GH_PKG_PREFIX }}${{ matrix.img_arch_prefix }}runimage:$GITHUB_SHA
          docker push ${{ env.GH_PKG_PREFIX }}${{ matrix.img_arch_prefix }}runimage:latest
          docker push ${{ env.GH_PKG_PREFIX }}runimage_${{ matrix.runimage_arch_name }}:$GITHUB_SHA
          docker push ${{ env.GH_PKG_PREFIX }}runimage_${{ matrix.runimage_arch_name }}:latest

      - name: Copy images to output folder
        shell: bash
        run: |
          rm -rf .dockersrv
          mkdir -p .dockersrv/output
          docker run \
            --rm \
            -v ${PWD}/.dockersrv:/srv \
            images_build_final \
            bash -c "cp -R /root/buildroot/output/images/ /srv/output/images/"

      - name: Upload images as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.runimage_arch_name }}_images
          path: |
            .dockersrv/output/images/vmlinux
            .dockersrv/output/images/rootfs.cpio.lz4
