name: Buildroot for ppc64_pseries arch


on:
  workflow_dispatch:


jobs:
  ppc64_pseries_toolchain:
    name: Buildroot toolchain
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Login to GitHub Package Registry
        shell: bash
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login https://docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Pull images from GitHub Package Registry
        shell: bash
        run: |
          docker pull docker.pkg.github.com/egraff/xplat-ci-images/buildroot:latest || true
          docker pull docker.pkg.github.com/egraff/xplat-ci-images/ppc64_pseries_toolchain_build:latest || true
          docker pull docker.pkg.github.com/egraff/xplat-ci-images/ppc64_pseries_toolchain:latest || true

      - name: Build buildroot base image
        run: docker build . --tag buildroot --file docker/buildroot.Dockerfile --cache-from docker.pkg.github.com/egraff/xplat-ci-images/buildroot:latest

      - name: Build buildroot toolchain build image
        run: docker build . --tag ppc64_pseries_toolchain_build --file docker/ppc64_pseries_toolchain_build.Dockerfile --cache-from docker.pkg.github.com/egraff/xplat-ci-images/ppc64_pseries_toolchain_build:latest

      - name: Build buildroot toolchain image
        run: docker build . --tag ppc64_pseries_toolchain --file docker/ppc64_pseries_toolchain.Dockerfile --cache-from docker.pkg.github.com/egraff/xplat-ci-images/ppc64_pseries_toolchain:latest

      - name: Create tar archive containing toolchain
        run: |
          rm -rf .dockersrv
          mkdir -p .dockersrv/output
          docker run --rm -v ${PWD}/.dockersrv:/srv -w/srv/output ppc64_pseries_toolchain tar -cvzf toolchain_ppc64_pseries.tar.gz -C /root/toolchain/ppc64_pseries/ .

      - name: Upload toolchain tar archive as artifact
        uses: actions/upload-artifact@v2
        with:
          name: toolchain_ppc64_pseries.tar.gz
          path: .dockersrv/output/toolchain_ppc64_pseries.tar.gz

      - name: Push to GitHub Packages
        shell: bash
        run: |
          docker tag buildroot docker.pkg.github.com/egraff/xplat-ci-images/buildroot:$GITHUB_SHA
          docker tag buildroot docker.pkg.github.com/egraff/xplat-ci-images/buildroot:latest
          docker tag ppc64_pseries_toolchain_build docker.pkg.github.com/egraff/xplat-ci-images/ppc64_pseries_toolchain_build:$GITHUB_SHA
          docker tag ppc64_pseries_toolchain_build docker.pkg.github.com/egraff/xplat-ci-images/ppc64_pseries_toolchain_build:latest
          docker tag ppc64_pseries_toolchain docker.pkg.github.com/egraff/xplat-ci-images/ppc64_pseries_toolchain:$GITHUB_SHA
          docker tag ppc64_pseries_toolchain docker.pkg.github.com/egraff/xplat-ci-images/ppc64_pseries_toolchain:latest
          docker push docker.pkg.github.com/egraff/xplat-ci-images/buildroot:$GITHUB_SHA
          docker push docker.pkg.github.com/egraff/xplat-ci-images/buildroot:latest
          docker push docker.pkg.github.com/egraff/xplat-ci-images/ppc64_pseries_toolchain_build:$GITHUB_SHA
          docker push docker.pkg.github.com/egraff/xplat-ci-images/ppc64_pseries_toolchain_build:latest
          docker push docker.pkg.github.com/egraff/xplat-ci-images/ppc64_pseries_toolchain:$GITHUB_SHA
          docker push docker.pkg.github.com/egraff/xplat-ci-images/ppc64_pseries_toolchain:latest

  ppc64_pseries_qemu_images:
    name: Buildroot images
    needs: ppc64_pseries_toolchain
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Login to GitHub Package Registry
        shell: bash
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login https://docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Pull images from GitHub Package Registry
        run: |
          docker pull docker.pkg.github.com/egraff/xplat-ci-images/buildroot:$GITHUB_SHA
          docker tag docker.pkg.github.com/egraff/xplat-ci-images/buildroot:$GITHUB_SHA buildroot
          docker pull docker.pkg.github.com/egraff/xplat-ci-images/ppc64_pseries_toolchain:$GITHUB_SHA
          docker tag docker.pkg.github.com/egraff/xplat-ci-images/ppc64_pseries_toolchain:$GITHUB_SHA ppc64_pseries_toolchain
          docker pull docker.pkg.github.com/egraff/xplat-ci-images/ppc64_pseries_images_build:latest || true

      - name: Download toolchain tar archive
        uses: actions/download-artifact@v2
        with:
          name: toolchain_ppc64_pseries.tar.gz

      - name: Extract toolchain tar
        run: |
          rm -rf .dockersrv
          mkdir -p .dockersrv/toolchain/ppc64_pseries
          tar -xvzf toolchain_ppc64_pseries.tar.gz -C .dockersrv/toolchain/ppc64_pseries/

      - name: Build buildroot images build image
        run: docker build . --tag ppc64_pseries_images_build --file docker/ppc64_pseries_images_build.Dockerfile --cache-from docker.pkg.github.com/egraff/xplat-ci-images/ppc64_pseries_images_build:latest

      - name: Push to GitHub Packages
        shell: bash
        run: |
          docker tag ppc64_pseries_images_build docker.pkg.github.com/egraff/xplat-ci-images/ppc64_pseries_images_build:$GITHUB_SHA
          docker tag ppc64_pseries_images_build docker.pkg.github.com/egraff/xplat-ci-images/ppc64_pseries_images_build:latest
          docker push docker.pkg.github.com/egraff/xplat-ci-images/ppc64_pseries_images_build:$GITHUB_SHA
          docker push docker.pkg.github.com/egraff/xplat-ci-images/ppc64_pseries_images_build:latest

      - name: Copy images to output folder
        shell: bash
        run: |
          rm -rf .dockersrv
          mkdir -p .dockersrv/output
          docker run --rm -v ${PWD}/.dockersrv:/srv ppc64_pseries_images_build bash -c "cp -R /root/buildroot-2020.02.7/output/images/ /srv/output/images/"

      - name: Upload images as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: images
          path: |
            .dockersrv/output/images/vmlinux
            .dockersrv/output/images/rootfs.cpio
